### ISSUE TITLE
Get up to date with vspark

### ISSUE THREAD

**Issue by marado** [kablamo/Term-Vspark#10]
https://github.com/LuRsT/vspark/commits/master adds a couple of things go vspark that weren't ported to Term-Vspark. It would be nice if Term-Vspark would have those, and also address its issues: https://github.com/LuRsT/vspark/issues .

**Comment by kablamo** [comment]
Thanks for pointing these out. Some of those look like problems I've had as well.  I'll take a look.  Patches welcome :)

**Comment by kablamo** [comment]
As far as I can tell I have resolved this issue.  Let me know if thats not the case.
