### ISSUE TITLE
Rename custom_char to char

### ISSUE THREAD

**Issue by kablamo** [kablamo/Term-Vspark#12]
I think I'm going to rename custom_char to char.

On a related note -- I don't really see the point of using all these characters in vspark: 
 ▏ ▎ ▍ ▌ ▋ ▊ ▉ █.  
When the graph is 80 chars wide its not a visible difference.  I think I'm going to just switch to using █ and round.

cc @marado -- let me know if you hate this

**Comment by LuRsT** [comment]
@kablamo, that's because the default case for vpsark is a one character chart, if you want the default case to be the whole length of the terminal, you can make do without them and simplify a lot of the code :).

**Comment by marado** [comment]
I'm OK with the renaming. 
As for the utf8 list of characters, I really have no use for them, so I'm probably not the best person to comment on them :-)

**Comment by kablamo** [comment]
@LuRsT thanks for pointing that out.  I kept those characters in.

I fixed many bugs. Wrote many tests.  Changed some default behavior.  Just did a release.  Let me know if it sucks.
